### ISSUE TITLE
Bot won't lunch on discords server 

### ISSUE THREAD

**Issue by Baylibrejmonnet** [nicoeg/discord-music-quizzer#5]
hi , if i try  ot lunche the bot with a public playlist `!music-quiz 37i9dQZEVXbMDoHDwVN2tF 10 both`
but it failed everytime.

```
Oh no... Youtube police busted the party :(
Please try again later.
```

exception catch 
`(node:3663) UnhandledPromiseRejectionWarning: Error: Failed to extract InitialData. The request may have been blocked.
    at /home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:258:27
    at new Promise (<anonymous>)
    at Youtube.extractInitialData (/home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:234:16)
    at Youtube.<anonymous> (/home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:193:55)
    at step (/home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:44:23)
    at Object.next (/home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:25:53)
    at /home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:15:12)
    at Request._callback (/home/jmonnet/discord-music-quizzer/node_modules/scrape-youtube/lib/index.js:180:112)
(node:3663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:3663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Issue seems to be fixe with your Proxy branch 

but with this branch , there no stream on voice channel from voice-quiz bot

**Comment by PerezdelaLamaJulien** [comment]
Hello, I have the same error. 
There is any setup to do before use the bot on the discord server? 
Thanks for the reply

**Comment by PenguinSnail** [comment]
I had the same issue at first and it looks like it's caused by out of date dependencies. I ran `npm upgrade` after installing dependencies and that fixed the issue.
